// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmuA3YBA8URY6jIwlnh3cknbx2XgiusHQ',
    appId: '1:99866406462:web:85296798be7bd39ce16b6f',
    messagingSenderId: '99866406462',
    projectId: 'allevents-demo',
    authDomain: 'allevents-demo.firebaseapp.com',
    storageBucket: 'allevents-demo.appspot.com',
    measurementId: 'G-SKZ8WYSFVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbE-3C25wr0vk12xlYoIN-ATurht9IDo',
    appId: '1:99866406462:android:3527f2d3ee86d2ede16b6f',
    messagingSenderId: '99866406462',
    projectId: 'allevents-demo',
    storageBucket: 'allevents-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwz2vB7nk6vJuVJ5ByMXo3sllSYJQpKcs',
    appId: '1:99866406462:ios:f8952c3eca0616c6e16b6f',
    messagingSenderId: '99866406462',
    projectId: 'allevents-demo',
    storageBucket: 'allevents-demo.appspot.com',
    iosBundleId: 'com.example.alleventsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwz2vB7nk6vJuVJ5ByMXo3sllSYJQpKcs',
    appId: '1:99866406462:ios:ce7b1ef290f09616e16b6f',
    messagingSenderId: '99866406462',
    projectId: 'allevents-demo',
    storageBucket: 'allevents-demo.appspot.com',
    iosBundleId: 'com.example.alleventsDemo.RunnerTests',
  );
}
